name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - run: 'nix profile install nixpkgs#nodejs_18 nixpkgs#nodePackages.pnpm'
      - run: pnpm install
      - run: tsc --noEmit